//
// Copyright 2020 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file src/api/yorkie/v1/yorkie.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivateClientRequest, ActivateClientResponse, AttachChannelRequest, AttachChannelResponse, AttachDocumentRequest, AttachDocumentResponse, BroadcastRequest, BroadcastResponse, CreateRevisionRequest, CreateRevisionResponse, DeactivateClientRequest, DeactivateClientResponse, DetachChannelRequest, DetachChannelResponse, DetachDocumentRequest, DetachDocumentResponse, ListRevisionsRequest, ListRevisionsResponse, PushPullChangesRequest, PushPullChangesResponse, RefreshChannelRequest, RefreshChannelResponse, RemoveDocumentRequest, RemoveDocumentResponse, RestoreRevisionRequest, RestoreRevisionResponse, WatchChannelRequest, WatchChannelResponse, WatchDocumentRequest, WatchDocumentResponse } from "./yorkie_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Yorkie is a service that provides an API for SDKs.
 *
 * @generated from service yorkie.v1.YorkieService
 */
export const YorkieService = {
  typeName: "yorkie.v1.YorkieService",
  methods: {
    /**
     * @generated from rpc yorkie.v1.YorkieService.ActivateClient
     */
    activateClient: {
      name: "ActivateClient",
      I: ActivateClientRequest,
      O: ActivateClientResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.DeactivateClient
     */
    deactivateClient: {
      name: "DeactivateClient",
      I: DeactivateClientRequest,
      O: DeactivateClientResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.AttachDocument
     */
    attachDocument: {
      name: "AttachDocument",
      I: AttachDocumentRequest,
      O: AttachDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.DetachDocument
     */
    detachDocument: {
      name: "DetachDocument",
      I: DetachDocumentRequest,
      O: DetachDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.RemoveDocument
     */
    removeDocument: {
      name: "RemoveDocument",
      I: RemoveDocumentRequest,
      O: RemoveDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.PushPullChanges
     */
    pushPullChanges: {
      name: "PushPullChanges",
      I: PushPullChangesRequest,
      O: PushPullChangesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.WatchDocument
     */
    watchDocument: {
      name: "WatchDocument",
      I: WatchDocumentRequest,
      O: WatchDocumentResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.CreateRevision
     */
    createRevision: {
      name: "CreateRevision",
      I: CreateRevisionRequest,
      O: CreateRevisionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.ListRevisions
     */
    listRevisions: {
      name: "ListRevisions",
      I: ListRevisionsRequest,
      O: ListRevisionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.RestoreRevision
     */
    restoreRevision: {
      name: "RestoreRevision",
      I: RestoreRevisionRequest,
      O: RestoreRevisionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.AttachChannel
     */
    attachChannel: {
      name: "AttachChannel",
      I: AttachChannelRequest,
      O: AttachChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.DetachChannel
     */
    detachChannel: {
      name: "DetachChannel",
      I: DetachChannelRequest,
      O: DetachChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.RefreshChannel
     */
    refreshChannel: {
      name: "RefreshChannel",
      I: RefreshChannelRequest,
      O: RefreshChannelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.WatchChannel
     */
    watchChannel: {
      name: "WatchChannel",
      I: WatchChannelRequest,
      O: WatchChannelResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.Broadcast
     */
    broadcast: {
      name: "Broadcast",
      I: BroadcastRequest,
      O: BroadcastResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

