//
// Copyright 2020 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts,js_import_style=module"
// @generated from file src/api/yorkie/v1/yorkie.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivateClientRequest, ActivateClientResponse, AttachDocumentRequest, AttachDocumentResponse, BroadcastRequest, BroadcastResponse, DeactivateClientRequest, DeactivateClientResponse, DetachDocumentRequest, DetachDocumentResponse, PushPullChangesRequest, PushPullChangesResponse, RemoveDocumentRequest, RemoveDocumentResponse, WatchDocumentRequest, WatchDocumentResponse } from "./yorkie_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Yorkie is a service that provides a API for SDKs.
 *
 * @generated from service yorkie.v1.YorkieService
 */
export declare const YorkieService: {
  readonly typeName: "yorkie.v1.YorkieService",
  readonly methods: {
    /**
     * @generated from rpc yorkie.v1.YorkieService.ActivateClient
     */
    readonly activateClient: {
      readonly name: "ActivateClient",
      readonly I: typeof ActivateClientRequest,
      readonly O: typeof ActivateClientResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.DeactivateClient
     */
    readonly deactivateClient: {
      readonly name: "DeactivateClient",
      readonly I: typeof DeactivateClientRequest,
      readonly O: typeof DeactivateClientResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.AttachDocument
     */
    readonly attachDocument: {
      readonly name: "AttachDocument",
      readonly I: typeof AttachDocumentRequest,
      readonly O: typeof AttachDocumentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.DetachDocument
     */
    readonly detachDocument: {
      readonly name: "DetachDocument",
      readonly I: typeof DetachDocumentRequest,
      readonly O: typeof DetachDocumentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.RemoveDocument
     */
    readonly removeDocument: {
      readonly name: "RemoveDocument",
      readonly I: typeof RemoveDocumentRequest,
      readonly O: typeof RemoveDocumentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.PushPullChanges
     */
    readonly pushPullChanges: {
      readonly name: "PushPullChanges",
      readonly I: typeof PushPullChangesRequest,
      readonly O: typeof PushPullChangesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.WatchDocument
     */
    readonly watchDocument: {
      readonly name: "WatchDocument",
      readonly I: typeof WatchDocumentRequest,
      readonly O: typeof WatchDocumentResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc yorkie.v1.YorkieService.Broadcast
     */
    readonly broadcast: {
      readonly name: "Broadcast",
      readonly I: typeof BroadcastRequest,
      readonly O: typeof BroadcastResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

