//
// Copyright 2020 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts,js_import_style=module"
// @generated from file src/api/yorkie/v1/yorkie.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { ChangePack, DocEvent } from "./resources_pb.js";

/**
 * @generated from message yorkie.v1.ActivateClientRequest
 */
export const ActivateClientRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.ActivateClientRequest",
  () => [
    { no: 1, name: "client_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.ActivateClientResponse
 */
export const ActivateClientResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.ActivateClientResponse",
  () => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.DeactivateClientRequest
 */
export const DeactivateClientRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.DeactivateClientRequest",
  () => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.DeactivateClientResponse
 */
export const DeactivateClientResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.DeactivateClientResponse",
  [],
);

/**
 * @generated from message yorkie.v1.AttachDocumentRequest
 */
export const AttachDocumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.AttachDocumentRequest",
  () => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "change_pack", kind: "message", T: ChangePack },
  ],
);

/**
 * @generated from message yorkie.v1.AttachDocumentResponse
 */
export const AttachDocumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.AttachDocumentResponse",
  () => [
    { no: 1, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "change_pack", kind: "message", T: ChangePack },
  ],
);

/**
 * @generated from message yorkie.v1.DetachDocumentRequest
 */
export const DetachDocumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.DetachDocumentRequest",
  () => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "change_pack", kind: "message", T: ChangePack },
    { no: 4, name: "remove_if_not_attached", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message yorkie.v1.DetachDocumentResponse
 */
export const DetachDocumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.DetachDocumentResponse",
  () => [
    { no: 2, name: "change_pack", kind: "message", T: ChangePack },
  ],
);

/**
 * @generated from message yorkie.v1.WatchDocumentRequest
 */
export const WatchDocumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.WatchDocumentRequest",
  () => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.WatchDocumentResponse
 */
export const WatchDocumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.WatchDocumentResponse",
  () => [
    { no: 1, name: "initialization", kind: "message", T: WatchDocumentResponse_Initialization, oneof: "body" },
    { no: 2, name: "event", kind: "message", T: DocEvent, oneof: "body" },
  ],
);

/**
 * @generated from message yorkie.v1.WatchDocumentResponse.Initialization
 */
export const WatchDocumentResponse_Initialization = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.WatchDocumentResponse.Initialization",
  () => [
    { no: 1, name: "client_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
  {localName: "WatchDocumentResponse_Initialization"},
);

/**
 * @generated from message yorkie.v1.RemoveDocumentRequest
 */
export const RemoveDocumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.RemoveDocumentRequest",
  () => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "change_pack", kind: "message", T: ChangePack },
  ],
);

/**
 * @generated from message yorkie.v1.RemoveDocumentResponse
 */
export const RemoveDocumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.RemoveDocumentResponse",
  () => [
    { no: 1, name: "change_pack", kind: "message", T: ChangePack },
  ],
);

/**
 * @generated from message yorkie.v1.PushPullChangesRequest
 */
export const PushPullChangesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.PushPullChangesRequest",
  () => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "change_pack", kind: "message", T: ChangePack },
    { no: 4, name: "push_only", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message yorkie.v1.PushPullChangesResponse
 */
export const PushPullChangesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.PushPullChangesResponse",
  () => [
    { no: 1, name: "change_pack", kind: "message", T: ChangePack },
  ],
);

/**
 * @generated from message yorkie.v1.BroadcastRequest
 */
export const BroadcastRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.BroadcastRequest",
  () => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "topic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message yorkie.v1.BroadcastResponse
 */
export const BroadcastResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.BroadcastResponse",
  [],
);

