import { describe, it, expect } from 'vitest';
import yorkie, { Document, Tree } from '@yorkie-js/sdk/src/yorkie';
import { TreeEditOperation } from '@yorkie-js/sdk/src/document/operation/tree_edit_operation';
import { traverseAll } from '@yorkie-js/sdk/src/util/index_tree';
import type { Operation } from '@yorkie-js/sdk/src/document/operation/operation';

/**
 * Single-client undo/redo regressions for `cloneAndDropPreTombstoned`.
 *
 * The reverseOp generated by a parent-delete must not resurrect
 * descendants the user had independently deleted in earlier ops. The
 * scenario reproduces wafflebase docs' production flow: insert a
 * sibling block, type into it, undo each char, then undo the block
 * insert. Without filtering, the redoStack-top reverseOp's contents
 * grow per cycle as previously-tombstoned descendants get cloned and
 * resurrected.
 */

function topRedoTreeEdit(
  doc: Document<{ t: Tree }>,
): TreeEditOperation | undefined {
  const stack = doc.getRedoStackForTest() as Array<Array<unknown>>;
  if (stack.length === 0) return undefined;
  const top = stack[stack.length - 1];
  for (let i = top.length - 1; i >= 0; i--) {
    const op = top[i];
    if (op instanceof TreeEditOperation) return op;
  }
  return undefined;
}

function summarizeOp(op: Operation | undefined): string {
  if (!(op instanceof TreeEditOperation)) return '<not-tree-edit>';
  const contents = op.getContents();
  if (!contents || contents.length === 0) return '(empty)';
  const parts: Array<string> = [];
  for (const root of contents) {
    traverseAll(root, (n) => {
      const created = n.id.getCreatedAt();
      const id = `L${created.getLamport()}/${created.getDelimiter()}`;
      const removed = n.removedAt ? `(R@L${n.removedAt.getLamport()})` : '';
      const val = n.isText ? `:"${n.value}"` : '';
      parts.push(`${n.type}${val}@${id}${removed}`);
    });
  }
  return `[${parts.length}] ${parts.join(' | ')}`;
}

function initDoc(): Document<{ t: Tree }> {
  const doc = new Document<{ t: Tree }>('split-repro');
  doc.update((root) => {
    root.t = new Tree({
      type: 'doc',
      children: [
        {
          type: 'p',
          children: [{ type: 'inline', children: [] }],
        },
      ],
    });
  }, 'init');
  return doc;
}

function insertSiblingBlock(doc: Document<{ t: Tree }>) {
  doc.update((root) => {
    root.t.editByPath([1], [1], {
      type: 'p',
      children: [{ type: 'inline', children: [] }],
    });
  }, 'insert-block');
}

// Insert one character at the end of the second <p>'s inline. Indices
// are computed from the visible XML so this works regardless of
// whether the inline also carries tombstoned children.
function typeInSecondBlock(doc: Document<{ t: Tree }>, ch: string) {
  doc.update((root) => {
    const xml = root.t.toXML();
    const m = xml.match(/<inline>([^<]*)<\/inline><\/p><\/doc>$/);
    const cur = m ? m[1].length : 0;
    root.t.editByPath([1, 0, cur], [1, 0, cur], {
      type: 'text',
      value: ch,
    });
  }, `type-${ch}`);
}

// 1. Single Client - reverseOp pre-tombstoned descendant filtering
describe('Tree History - single client reverseOp pre-tombstoned filter', () => {
  it('should not accumulate reverseOp contents across redo cycles', () => {
    const doc = initDoc();
    insertSiblingBlock(doc);

    const numCycles = 4;
    const redoOpSizes: Array<number> = [];

    for (let cycle = 0; cycle < numCycles; cycle++) {
      // Type "asdf" in the inserted block.
      for (const ch of 'asdf') typeInSecondBlock(doc, ch);

      // Undo each char.
      for (let i = 0; i < 4; i++) doc.history.undo();

      // Undo the block-insert. After this, redoStack's top is the op
      // that the next history.redo() will execute. That op's
      // `contents` is the wire payload observed in production.
      doc.history.undo();

      const redoTop = topRedoTreeEdit(doc);
      let count = 0;
      const contents = redoTop?.getContents() ?? [];
      for (const root of contents) traverseAll(root, () => count++);
      redoOpSizes.push(count);

      process.stdout.write(
        `cycle ${cycle}: redoStack top = ${summarizeOp(redoTop)}\n`,
      );

      // Now actually redo for the next cycle's setup.
      doc.history.redo();
    }

    expect(redoOpSizes).toStrictEqual(Array(numCycles).fill(redoOpSizes[0]));
  });

  it('should produce reverseContents with consistent sizes', () => {
    const doc = initDoc();
    insertSiblingBlock(doc);

    for (const ch of 'asdf') typeInSecondBlock(doc, ch);
    for (let i = 0; i < 4; i++) doc.history.undo();
    doc.history.undo();

    const redoTop = topRedoTreeEdit(doc);
    expect(redoTop).toBeDefined();
    const contents = redoTop!.getContents() ?? [];
    expect(contents.length).toBeGreaterThan(0);

    // For each surviving element node in `reverseContents`, the
    // post-filter `totalSize` must equal the sum of its children's
    // `paddedSize`. Without bottom-up recomputation the deepcopy
    // carries the live tree's stale total, which includes the
    // descendants that were just dropped from `_children`.
    const violations: Array<string> = [];
    for (const root of contents) {
      traverseAll(root, (n) => {
        if (n.isText) return;
        const expected = n._children.reduce(
          (acc, child) => acc + child.paddedSize(),
          0,
        );
        if (n.totalSize !== expected || n.visibleSize !== expected) {
          violations.push(
            `${n.type}: totalSize=${n.totalSize} visibleSize=${n.visibleSize} ` +
              `expected=${expected} (children=${n._children.length})`,
          );
        }
      });
    }
    expect(violations).toStrictEqual([]);
  });

  it('should allow typing at the correct position after redo', () => {
    const doc = initDoc();
    insertSiblingBlock(doc);

    for (const ch of 'asdf') typeInSecondBlock(doc, ch);
    for (let i = 0; i < 4; i++) doc.history.undo();
    doc.history.undo();
    expect(doc.getRoot().t.toXML()).toBe('<doc><p><inline></inline></p></doc>');

    doc.history.redo();
    expect(doc.getRoot().t.toXML()).toBe(
      '<doc><p><inline></inline></p><p><inline></inline></p></doc>',
    );

    typeInSecondBlock(doc, 'x');
    expect(doc.getRoot().t.toXML()).toBe(
      '<doc><p><inline></inline></p><p><inline>x</inline></p></doc>',
    );
  });

  it('should remain stable across three cycles followed by typing', () => {
    const doc = initDoc();
    insertSiblingBlock(doc);

    for (let cycle = 0; cycle < 3; cycle++) {
      for (const ch of 'asdf') typeInSecondBlock(doc, ch);
      for (let i = 0; i < 4; i++) doc.history.undo();
      doc.history.undo();
      doc.history.redo();
      expect(doc.getRoot().t.toXML()).toBe(
        '<doc><p><inline></inline></p><p><inline></inline></p></doc>',
      );
    }

    typeInSecondBlock(doc, 'z');
    expect(doc.getRoot().t.toXML()).toBe(
      '<doc><p><inline></inline></p><p><inline>z</inline></p></doc>',
    );
  });
});

void yorkie;
