//
// Copyright 2022 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.6.0 with parameter "target=js+dts,js_import_style=legacy_commonjs"
// @generated from file src/api/yorkie/v1/resources.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum yorkie.v1.ValueType
 */
export declare enum ValueType {
  /**
   * @generated from enum value: VALUE_TYPE_NULL = 0;
   */
  NULL = 0,

  /**
   * @generated from enum value: VALUE_TYPE_BOOLEAN = 1;
   */
  BOOLEAN = 1,

  /**
   * @generated from enum value: VALUE_TYPE_INTEGER = 2;
   */
  INTEGER = 2,

  /**
   * @generated from enum value: VALUE_TYPE_LONG = 3;
   */
  LONG = 3,

  /**
   * @generated from enum value: VALUE_TYPE_DOUBLE = 4;
   */
  DOUBLE = 4,

  /**
   * @generated from enum value: VALUE_TYPE_STRING = 5;
   */
  STRING = 5,

  /**
   * @generated from enum value: VALUE_TYPE_BYTES = 6;
   */
  BYTES = 6,

  /**
   * @generated from enum value: VALUE_TYPE_DATE = 7;
   */
  DATE = 7,

  /**
   * @generated from enum value: VALUE_TYPE_JSON_OBJECT = 8;
   */
  JSON_OBJECT = 8,

  /**
   * @generated from enum value: VALUE_TYPE_JSON_ARRAY = 9;
   */
  JSON_ARRAY = 9,

  /**
   * @generated from enum value: VALUE_TYPE_TEXT = 10;
   */
  TEXT = 10,

  /**
   * @generated from enum value: VALUE_TYPE_INTEGER_CNT = 11;
   */
  INTEGER_CNT = 11,

  /**
   * @generated from enum value: VALUE_TYPE_LONG_CNT = 12;
   */
  LONG_CNT = 12,

  /**
   * @generated from enum value: VALUE_TYPE_TREE = 13;
   */
  TREE = 13,
}

/**
 * @generated from enum yorkie.v1.DocEventType
 */
export declare enum DocEventType {
  /**
   * @generated from enum value: DOC_EVENT_TYPE_DOCUMENT_CHANGED = 0;
   */
  DOCUMENT_CHANGED = 0,

  /**
   * @generated from enum value: DOC_EVENT_TYPE_DOCUMENT_WATCHED = 1;
   */
  DOCUMENT_WATCHED = 1,

  /**
   * @generated from enum value: DOC_EVENT_TYPE_DOCUMENT_UNWATCHED = 2;
   */
  DOCUMENT_UNWATCHED = 2,

  /**
   * @generated from enum value: DOC_EVENT_TYPE_DOCUMENT_BROADCAST = 3;
   */
  DOCUMENT_BROADCAST = 3,
}

/**
 * ///////////////////////////////////////
 * Messages for Snapshot               //
 * ///////////////////////////////////////
 *
 * @generated from message yorkie.v1.Snapshot
 */
export declare class Snapshot extends Message<Snapshot> {
  /**
   * @generated from field: yorkie.v1.JSONElement root = 1;
   */
  root?: JSONElement;

  /**
   * @generated from field: map<string, yorkie.v1.Presence> presences = 2;
   */
  presences: { [key: string]: Presence };

  constructor(data?: PartialMessage<Snapshot>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Snapshot";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Snapshot;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Snapshot;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Snapshot;

  static equals(a: Snapshot | PlainMessage<Snapshot> | undefined, b: Snapshot | PlainMessage<Snapshot> | undefined): boolean;
}

/**
 * ChangePack is a message that contains all changes that occurred in a document.
 * It is used to synchronize changes between clients and servers.
 *
 * @generated from message yorkie.v1.ChangePack
 */
export declare class ChangePack extends Message<ChangePack> {
  /**
   * @generated from field: string document_key = 1;
   */
  documentKey: string;

  /**
   * @generated from field: yorkie.v1.Checkpoint checkpoint = 2;
   */
  checkpoint?: Checkpoint;

  /**
   * @generated from field: bytes snapshot = 3;
   */
  snapshot: Uint8Array;

  /**
   * @generated from field: repeated yorkie.v1.Change changes = 4;
   */
  changes: Change[];

  /**
   * @generated from field: yorkie.v1.TimeTicket min_synced_ticket = 5;
   */
  minSyncedTicket?: TimeTicket;

  /**
   * @generated from field: bool is_removed = 6;
   */
  isRemoved: boolean;

  constructor(data?: PartialMessage<ChangePack>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.ChangePack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChangePack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChangePack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChangePack;

  static equals(a: ChangePack | PlainMessage<ChangePack> | undefined, b: ChangePack | PlainMessage<ChangePack> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Change
 */
export declare class Change extends Message<Change> {
  /**
   * @generated from field: yorkie.v1.ChangeID id = 1;
   */
  id?: ChangeID;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated yorkie.v1.Operation operations = 3;
   */
  operations: Operation[];

  /**
   * @generated from field: yorkie.v1.PresenceChange presence_change = 4;
   */
  presenceChange?: PresenceChange;

  constructor(data?: PartialMessage<Change>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Change";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Change;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Change;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Change;

  static equals(a: Change | PlainMessage<Change> | undefined, b: Change | PlainMessage<Change> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.ChangeID
 */
export declare class ChangeID extends Message<ChangeID> {
  /**
   * @generated from field: uint32 client_seq = 1;
   */
  clientSeq: number;

  /**
   * @generated from field: int64 server_seq = 2 [jstype = JS_STRING];
   */
  serverSeq: string;

  /**
   * @generated from field: int64 lamport = 3 [jstype = JS_STRING];
   */
  lamport: string;

  /**
   * @generated from field: bytes actor_id = 4;
   */
  actorId: Uint8Array;

  constructor(data?: PartialMessage<ChangeID>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.ChangeID";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ChangeID;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ChangeID;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ChangeID;

  static equals(a: ChangeID | PlainMessage<ChangeID> | undefined, b: ChangeID | PlainMessage<ChangeID> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation
 */
export declare class Operation extends Message<Operation> {
  /**
   * @generated from oneof yorkie.v1.Operation.body
   */
  body: {
    /**
     * @generated from field: yorkie.v1.Operation.Set set = 1;
     */
    value: Operation_Set;
    case: "set";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.Add add = 2;
     */
    value: Operation_Add;
    case: "add";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.Move move = 3;
     */
    value: Operation_Move;
    case: "move";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.Remove remove = 4;
     */
    value: Operation_Remove;
    case: "remove";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.Edit edit = 5;
     */
    value: Operation_Edit;
    case: "edit";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.Select select = 6;
     */
    value: Operation_Select;
    case: "select";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.Style style = 7;
     */
    value: Operation_Style;
    case: "style";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.Increase increase = 8;
     */
    value: Operation_Increase;
    case: "increase";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.TreeEdit tree_edit = 9;
     */
    value: Operation_TreeEdit;
    case: "treeEdit";
  } | {
    /**
     * @generated from field: yorkie.v1.Operation.TreeStyle tree_style = 10;
     */
    value: Operation_TreeStyle;
    case: "treeStyle";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<Operation>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation;

  static equals(a: Operation | PlainMessage<Operation> | undefined, b: Operation | PlainMessage<Operation> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.Set
 */
export declare class Operation_Set extends Message<Operation_Set> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * @generated from field: yorkie.v1.JSONElementSimple value = 3;
   */
  value?: JSONElementSimple;

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 4;
   */
  executedAt?: TimeTicket;

  constructor(data?: PartialMessage<Operation_Set>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.Set";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_Set;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_Set;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_Set;

  static equals(a: Operation_Set | PlainMessage<Operation_Set> | undefined, b: Operation_Set | PlainMessage<Operation_Set> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.Add
 */
export declare class Operation_Add extends Message<Operation_Add> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket prev_created_at = 2;
   */
  prevCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.JSONElementSimple value = 3;
   */
  value?: JSONElementSimple;

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 4;
   */
  executedAt?: TimeTicket;

  constructor(data?: PartialMessage<Operation_Add>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.Add";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_Add;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_Add;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_Add;

  static equals(a: Operation_Add | PlainMessage<Operation_Add> | undefined, b: Operation_Add | PlainMessage<Operation_Add> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.Move
 */
export declare class Operation_Move extends Message<Operation_Move> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket prev_created_at = 2;
   */
  prevCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 3;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 4;
   */
  executedAt?: TimeTicket;

  constructor(data?: PartialMessage<Operation_Move>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.Move";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_Move;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_Move;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_Move;

  static equals(a: Operation_Move | PlainMessage<Operation_Move> | undefined, b: Operation_Move | PlainMessage<Operation_Move> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.Remove
 */
export declare class Operation_Remove extends Message<Operation_Remove> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 2;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 3;
   */
  executedAt?: TimeTicket;

  constructor(data?: PartialMessage<Operation_Remove>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.Remove";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_Remove;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_Remove;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_Remove;

  static equals(a: Operation_Remove | PlainMessage<Operation_Remove> | undefined, b: Operation_Remove | PlainMessage<Operation_Remove> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.Edit
 */
export declare class Operation_Edit extends Message<Operation_Edit> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TextNodePos from = 2;
   */
  from?: TextNodePos;

  /**
   * @generated from field: yorkie.v1.TextNodePos to = 3;
   */
  to?: TextNodePos;

  /**
   * @generated from field: map<string, yorkie.v1.TimeTicket> created_at_map_by_actor = 4;
   */
  createdAtMapByActor: { [key: string]: TimeTicket };

  /**
   * @generated from field: string content = 5;
   */
  content: string;

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 6;
   */
  executedAt?: TimeTicket;

  /**
   * @generated from field: map<string, string> attributes = 7;
   */
  attributes: { [key: string]: string };

  constructor(data?: PartialMessage<Operation_Edit>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.Edit";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_Edit;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_Edit;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_Edit;

  static equals(a: Operation_Edit | PlainMessage<Operation_Edit> | undefined, b: Operation_Edit | PlainMessage<Operation_Edit> | undefined): boolean;
}

/**
 * NOTE(hackerwins): Select Operation is not used in the current version.
 * In the previous version, it was used to represent selection of Text.
 * However, it has been replaced by Presence now. It is retained for backward
 * compatibility purposes.
 *
 * @generated from message yorkie.v1.Operation.Select
 */
export declare class Operation_Select extends Message<Operation_Select> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TextNodePos from = 2;
   */
  from?: TextNodePos;

  /**
   * @generated from field: yorkie.v1.TextNodePos to = 3;
   */
  to?: TextNodePos;

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 4;
   */
  executedAt?: TimeTicket;

  constructor(data?: PartialMessage<Operation_Select>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.Select";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_Select;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_Select;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_Select;

  static equals(a: Operation_Select | PlainMessage<Operation_Select> | undefined, b: Operation_Select | PlainMessage<Operation_Select> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.Style
 */
export declare class Operation_Style extends Message<Operation_Style> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TextNodePos from = 2;
   */
  from?: TextNodePos;

  /**
   * @generated from field: yorkie.v1.TextNodePos to = 3;
   */
  to?: TextNodePos;

  /**
   * @generated from field: map<string, string> attributes = 4;
   */
  attributes: { [key: string]: string };

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 5;
   */
  executedAt?: TimeTicket;

  /**
   * @generated from field: map<string, yorkie.v1.TimeTicket> created_at_map_by_actor = 6;
   */
  createdAtMapByActor: { [key: string]: TimeTicket };

  constructor(data?: PartialMessage<Operation_Style>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.Style";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_Style;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_Style;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_Style;

  static equals(a: Operation_Style | PlainMessage<Operation_Style> | undefined, b: Operation_Style | PlainMessage<Operation_Style> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.Increase
 */
export declare class Operation_Increase extends Message<Operation_Increase> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.JSONElementSimple value = 2;
   */
  value?: JSONElementSimple;

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 3;
   */
  executedAt?: TimeTicket;

  constructor(data?: PartialMessage<Operation_Increase>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.Increase";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_Increase;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_Increase;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_Increase;

  static equals(a: Operation_Increase | PlainMessage<Operation_Increase> | undefined, b: Operation_Increase | PlainMessage<Operation_Increase> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.TreeEdit
 */
export declare class Operation_TreeEdit extends Message<Operation_TreeEdit> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TreePos from = 2;
   */
  from?: TreePos;

  /**
   * @generated from field: yorkie.v1.TreePos to = 3;
   */
  to?: TreePos;

  /**
   * @generated from field: map<string, yorkie.v1.TimeTicket> created_at_map_by_actor = 4;
   */
  createdAtMapByActor: { [key: string]: TimeTicket };

  /**
   * @generated from field: repeated yorkie.v1.TreeNodes contents = 5;
   */
  contents: TreeNodes[];

  /**
   * @generated from field: int32 split_level = 7;
   */
  splitLevel: number;

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 6;
   */
  executedAt?: TimeTicket;

  constructor(data?: PartialMessage<Operation_TreeEdit>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.TreeEdit";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_TreeEdit;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_TreeEdit;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_TreeEdit;

  static equals(a: Operation_TreeEdit | PlainMessage<Operation_TreeEdit> | undefined, b: Operation_TreeEdit | PlainMessage<Operation_TreeEdit> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Operation.TreeStyle
 */
export declare class Operation_TreeStyle extends Message<Operation_TreeStyle> {
  /**
   * @generated from field: yorkie.v1.TimeTicket parent_created_at = 1;
   */
  parentCreatedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TreePos from = 2;
   */
  from?: TreePos;

  /**
   * @generated from field: yorkie.v1.TreePos to = 3;
   */
  to?: TreePos;

  /**
   * @generated from field: map<string, string> attributes = 4;
   */
  attributes: { [key: string]: string };

  /**
   * @generated from field: yorkie.v1.TimeTicket executed_at = 5;
   */
  executedAt?: TimeTicket;

  /**
   * @generated from field: repeated string attributes_to_remove = 6;
   */
  attributesToRemove: string[];

  /**
   * @generated from field: map<string, yorkie.v1.TimeTicket> created_at_map_by_actor = 7;
   */
  createdAtMapByActor: { [key: string]: TimeTicket };

  constructor(data?: PartialMessage<Operation_TreeStyle>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Operation.TreeStyle";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Operation_TreeStyle;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Operation_TreeStyle;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Operation_TreeStyle;

  static equals(a: Operation_TreeStyle | PlainMessage<Operation_TreeStyle> | undefined, b: Operation_TreeStyle | PlainMessage<Operation_TreeStyle> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.JSONElementSimple
 */
export declare class JSONElementSimple extends Message<JSONElementSimple> {
  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 1;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket moved_at = 2;
   */
  movedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 3;
   */
  removedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.ValueType type = 4;
   */
  type: ValueType;

  /**
   * @generated from field: bytes value = 5;
   */
  value: Uint8Array;

  constructor(data?: PartialMessage<JSONElementSimple>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.JSONElementSimple";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JSONElementSimple;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JSONElementSimple;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JSONElementSimple;

  static equals(a: JSONElementSimple | PlainMessage<JSONElementSimple> | undefined, b: JSONElementSimple | PlainMessage<JSONElementSimple> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.JSONElement
 */
export declare class JSONElement extends Message<JSONElement> {
  /**
   * @generated from oneof yorkie.v1.JSONElement.body
   */
  body: {
    /**
     * @generated from field: yorkie.v1.JSONElement.JSONObject json_object = 1;
     */
    value: JSONElement_JSONObject;
    case: "jsonObject";
  } | {
    /**
     * @generated from field: yorkie.v1.JSONElement.JSONArray json_array = 2;
     */
    value: JSONElement_JSONArray;
    case: "jsonArray";
  } | {
    /**
     * @generated from field: yorkie.v1.JSONElement.Primitive primitive = 3;
     */
    value: JSONElement_Primitive;
    case: "primitive";
  } | {
    /**
     * @generated from field: yorkie.v1.JSONElement.Text text = 5;
     */
    value: JSONElement_Text;
    case: "text";
  } | {
    /**
     * @generated from field: yorkie.v1.JSONElement.Counter counter = 6;
     */
    value: JSONElement_Counter;
    case: "counter";
  } | {
    /**
     * @generated from field: yorkie.v1.JSONElement.Tree tree = 7;
     */
    value: JSONElement_Tree;
    case: "tree";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<JSONElement>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.JSONElement";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JSONElement;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JSONElement;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JSONElement;

  static equals(a: JSONElement | PlainMessage<JSONElement> | undefined, b: JSONElement | PlainMessage<JSONElement> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.JSONElement.JSONObject
 */
export declare class JSONElement_JSONObject extends Message<JSONElement_JSONObject> {
  /**
   * @generated from field: repeated yorkie.v1.RHTNode nodes = 1;
   */
  nodes: RHTNode[];

  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 2;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket moved_at = 3;
   */
  movedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 4;
   */
  removedAt?: TimeTicket;

  constructor(data?: PartialMessage<JSONElement_JSONObject>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.JSONElement.JSONObject";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JSONElement_JSONObject;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JSONElement_JSONObject;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JSONElement_JSONObject;

  static equals(a: JSONElement_JSONObject | PlainMessage<JSONElement_JSONObject> | undefined, b: JSONElement_JSONObject | PlainMessage<JSONElement_JSONObject> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.JSONElement.JSONArray
 */
export declare class JSONElement_JSONArray extends Message<JSONElement_JSONArray> {
  /**
   * @generated from field: repeated yorkie.v1.RGANode nodes = 1;
   */
  nodes: RGANode[];

  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 2;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket moved_at = 3;
   */
  movedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 4;
   */
  removedAt?: TimeTicket;

  constructor(data?: PartialMessage<JSONElement_JSONArray>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.JSONElement.JSONArray";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JSONElement_JSONArray;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JSONElement_JSONArray;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JSONElement_JSONArray;

  static equals(a: JSONElement_JSONArray | PlainMessage<JSONElement_JSONArray> | undefined, b: JSONElement_JSONArray | PlainMessage<JSONElement_JSONArray> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.JSONElement.Primitive
 */
export declare class JSONElement_Primitive extends Message<JSONElement_Primitive> {
  /**
   * @generated from field: yorkie.v1.ValueType type = 1;
   */
  type: ValueType;

  /**
   * @generated from field: bytes value = 2;
   */
  value: Uint8Array;

  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 3;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket moved_at = 4;
   */
  movedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 5;
   */
  removedAt?: TimeTicket;

  constructor(data?: PartialMessage<JSONElement_Primitive>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.JSONElement.Primitive";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JSONElement_Primitive;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JSONElement_Primitive;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JSONElement_Primitive;

  static equals(a: JSONElement_Primitive | PlainMessage<JSONElement_Primitive> | undefined, b: JSONElement_Primitive | PlainMessage<JSONElement_Primitive> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.JSONElement.Text
 */
export declare class JSONElement_Text extends Message<JSONElement_Text> {
  /**
   * @generated from field: repeated yorkie.v1.TextNode nodes = 1;
   */
  nodes: TextNode[];

  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 2;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket moved_at = 3;
   */
  movedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 4;
   */
  removedAt?: TimeTicket;

  constructor(data?: PartialMessage<JSONElement_Text>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.JSONElement.Text";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JSONElement_Text;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JSONElement_Text;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JSONElement_Text;

  static equals(a: JSONElement_Text | PlainMessage<JSONElement_Text> | undefined, b: JSONElement_Text | PlainMessage<JSONElement_Text> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.JSONElement.Counter
 */
export declare class JSONElement_Counter extends Message<JSONElement_Counter> {
  /**
   * @generated from field: yorkie.v1.ValueType type = 1;
   */
  type: ValueType;

  /**
   * @generated from field: bytes value = 2;
   */
  value: Uint8Array;

  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 3;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket moved_at = 4;
   */
  movedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 5;
   */
  removedAt?: TimeTicket;

  constructor(data?: PartialMessage<JSONElement_Counter>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.JSONElement.Counter";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JSONElement_Counter;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JSONElement_Counter;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JSONElement_Counter;

  static equals(a: JSONElement_Counter | PlainMessage<JSONElement_Counter> | undefined, b: JSONElement_Counter | PlainMessage<JSONElement_Counter> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.JSONElement.Tree
 */
export declare class JSONElement_Tree extends Message<JSONElement_Tree> {
  /**
   * @generated from field: repeated yorkie.v1.TreeNode nodes = 1;
   */
  nodes: TreeNode[];

  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 2;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket moved_at = 3;
   */
  movedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 4;
   */
  removedAt?: TimeTicket;

  constructor(data?: PartialMessage<JSONElement_Tree>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.JSONElement.Tree";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JSONElement_Tree;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JSONElement_Tree;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JSONElement_Tree;

  static equals(a: JSONElement_Tree | PlainMessage<JSONElement_Tree> | undefined, b: JSONElement_Tree | PlainMessage<JSONElement_Tree> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.RHTNode
 */
export declare class RHTNode extends Message<RHTNode> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: yorkie.v1.JSONElement element = 2;
   */
  element?: JSONElement;

  constructor(data?: PartialMessage<RHTNode>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.RHTNode";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RHTNode;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RHTNode;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RHTNode;

  static equals(a: RHTNode | PlainMessage<RHTNode> | undefined, b: RHTNode | PlainMessage<RHTNode> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.RGANode
 */
export declare class RGANode extends Message<RGANode> {
  /**
   * @generated from field: yorkie.v1.RGANode next = 1;
   */
  next?: RGANode;

  /**
   * @generated from field: yorkie.v1.JSONElement element = 2;
   */
  element?: JSONElement;

  constructor(data?: PartialMessage<RGANode>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.RGANode";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RGANode;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RGANode;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RGANode;

  static equals(a: RGANode | PlainMessage<RGANode> | undefined, b: RGANode | PlainMessage<RGANode> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.NodeAttr
 */
export declare class NodeAttr extends Message<NodeAttr> {
  /**
   * @generated from field: string value = 1;
   */
  value: string;

  /**
   * @generated from field: yorkie.v1.TimeTicket updated_at = 2;
   */
  updatedAt?: TimeTicket;

  constructor(data?: PartialMessage<NodeAttr>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.NodeAttr";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NodeAttr;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NodeAttr;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NodeAttr;

  static equals(a: NodeAttr | PlainMessage<NodeAttr> | undefined, b: NodeAttr | PlainMessage<NodeAttr> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.TextNode
 */
export declare class TextNode extends Message<TextNode> {
  /**
   * @generated from field: yorkie.v1.TextNodeID id = 1;
   */
  id?: TextNodeID;

  /**
   * @generated from field: string value = 2;
   */
  value: string;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 3;
   */
  removedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TextNodeID ins_prev_id = 4;
   */
  insPrevId?: TextNodeID;

  /**
   * @generated from field: map<string, yorkie.v1.NodeAttr> attributes = 5;
   */
  attributes: { [key: string]: NodeAttr };

  constructor(data?: PartialMessage<TextNode>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.TextNode";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TextNode;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TextNode;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TextNode;

  static equals(a: TextNode | PlainMessage<TextNode> | undefined, b: TextNode | PlainMessage<TextNode> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.TextNodeID
 */
export declare class TextNodeID extends Message<TextNodeID> {
  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 1;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  constructor(data?: PartialMessage<TextNodeID>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.TextNodeID";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TextNodeID;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TextNodeID;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TextNodeID;

  static equals(a: TextNodeID | PlainMessage<TextNodeID> | undefined, b: TextNodeID | PlainMessage<TextNodeID> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.TreeNode
 */
export declare class TreeNode extends Message<TreeNode> {
  /**
   * @generated from field: yorkie.v1.TreeNodeID id = 1;
   */
  id?: TreeNodeID;

  /**
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: string value = 3;
   */
  value: string;

  /**
   * @generated from field: yorkie.v1.TimeTicket removed_at = 4;
   */
  removedAt?: TimeTicket;

  /**
   * @generated from field: yorkie.v1.TreeNodeID ins_prev_id = 5;
   */
  insPrevId?: TreeNodeID;

  /**
   * @generated from field: yorkie.v1.TreeNodeID ins_next_id = 6;
   */
  insNextId?: TreeNodeID;

  /**
   * @generated from field: int32 depth = 7;
   */
  depth: number;

  /**
   * @generated from field: map<string, yorkie.v1.NodeAttr> attributes = 8;
   */
  attributes: { [key: string]: NodeAttr };

  constructor(data?: PartialMessage<TreeNode>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.TreeNode";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TreeNode;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TreeNode;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TreeNode;

  static equals(a: TreeNode | PlainMessage<TreeNode> | undefined, b: TreeNode | PlainMessage<TreeNode> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.TreeNodes
 */
export declare class TreeNodes extends Message<TreeNodes> {
  /**
   * @generated from field: repeated yorkie.v1.TreeNode content = 1;
   */
  content: TreeNode[];

  constructor(data?: PartialMessage<TreeNodes>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.TreeNodes";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TreeNodes;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TreeNodes;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TreeNodes;

  static equals(a: TreeNodes | PlainMessage<TreeNodes> | undefined, b: TreeNodes | PlainMessage<TreeNodes> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.TreeNodeID
 */
export declare class TreeNodeID extends Message<TreeNodeID> {
  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 1;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  constructor(data?: PartialMessage<TreeNodeID>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.TreeNodeID";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TreeNodeID;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TreeNodeID;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TreeNodeID;

  static equals(a: TreeNodeID | PlainMessage<TreeNodeID> | undefined, b: TreeNodeID | PlainMessage<TreeNodeID> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.TreePos
 */
export declare class TreePos extends Message<TreePos> {
  /**
   * @generated from field: yorkie.v1.TreeNodeID parent_id = 1;
   */
  parentId?: TreeNodeID;

  /**
   * @generated from field: yorkie.v1.TreeNodeID left_sibling_id = 2;
   */
  leftSiblingId?: TreeNodeID;

  constructor(data?: PartialMessage<TreePos>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.TreePos";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TreePos;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TreePos;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TreePos;

  static equals(a: TreePos | PlainMessage<TreePos> | undefined, b: TreePos | PlainMessage<TreePos> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.User
 */
export declare class User extends Message<User> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<User>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.User";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User;

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Project
 */
export declare class Project extends Message<Project> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string public_key = 3;
   */
  publicKey: string;

  /**
   * @generated from field: string secret_key = 4;
   */
  secretKey: string;

  /**
   * @generated from field: string auth_webhook_url = 5;
   */
  authWebhookUrl: string;

  /**
   * @generated from field: repeated string auth_webhook_methods = 6;
   */
  authWebhookMethods: string[];

  /**
   * @generated from field: string client_deactivate_threshold = 7;
   */
  clientDeactivateThreshold: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Project>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Project";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Project;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Project;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Project;

  static equals(a: Project | PlainMessage<Project> | undefined, b: Project | PlainMessage<Project> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.UpdatableProjectFields
 */
export declare class UpdatableProjectFields extends Message<UpdatableProjectFields> {
  /**
   * @generated from field: google.protobuf.StringValue name = 1;
   */
  name?: string;

  /**
   * @generated from field: google.protobuf.StringValue auth_webhook_url = 2;
   */
  authWebhookUrl?: string;

  /**
   * @generated from field: yorkie.v1.UpdatableProjectFields.AuthWebhookMethods auth_webhook_methods = 3;
   */
  authWebhookMethods?: UpdatableProjectFields_AuthWebhookMethods;

  /**
   * @generated from field: google.protobuf.StringValue client_deactivate_threshold = 4;
   */
  clientDeactivateThreshold?: string;

  constructor(data?: PartialMessage<UpdatableProjectFields>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.UpdatableProjectFields";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdatableProjectFields;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdatableProjectFields;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdatableProjectFields;

  static equals(a: UpdatableProjectFields | PlainMessage<UpdatableProjectFields> | undefined, b: UpdatableProjectFields | PlainMessage<UpdatableProjectFields> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.UpdatableProjectFields.AuthWebhookMethods
 */
export declare class UpdatableProjectFields_AuthWebhookMethods extends Message<UpdatableProjectFields_AuthWebhookMethods> {
  /**
   * @generated from field: repeated string methods = 1;
   */
  methods: string[];

  constructor(data?: PartialMessage<UpdatableProjectFields_AuthWebhookMethods>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.UpdatableProjectFields.AuthWebhookMethods";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdatableProjectFields_AuthWebhookMethods;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdatableProjectFields_AuthWebhookMethods;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdatableProjectFields_AuthWebhookMethods;

  static equals(a: UpdatableProjectFields_AuthWebhookMethods | PlainMessage<UpdatableProjectFields_AuthWebhookMethods> | undefined, b: UpdatableProjectFields_AuthWebhookMethods | PlainMessage<UpdatableProjectFields_AuthWebhookMethods> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.DocumentSummary
 */
export declare class DocumentSummary extends Message<DocumentSummary> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * @generated from field: string snapshot = 3;
   */
  snapshot: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp accessed_at = 5;
   */
  accessedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<DocumentSummary>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.DocumentSummary";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocumentSummary;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocumentSummary;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocumentSummary;

  static equals(a: DocumentSummary | PlainMessage<DocumentSummary> | undefined, b: DocumentSummary | PlainMessage<DocumentSummary> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.PresenceChange
 */
export declare class PresenceChange extends Message<PresenceChange> {
  /**
   * @generated from field: yorkie.v1.PresenceChange.ChangeType type = 1;
   */
  type: PresenceChange_ChangeType;

  /**
   * @generated from field: yorkie.v1.Presence presence = 2;
   */
  presence?: Presence;

  constructor(data?: PartialMessage<PresenceChange>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.PresenceChange";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PresenceChange;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PresenceChange;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PresenceChange;

  static equals(a: PresenceChange | PlainMessage<PresenceChange> | undefined, b: PresenceChange | PlainMessage<PresenceChange> | undefined): boolean;
}

/**
 * @generated from enum yorkie.v1.PresenceChange.ChangeType
 */
export declare enum PresenceChange_ChangeType {
  /**
   * @generated from enum value: CHANGE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CHANGE_TYPE_PUT = 1;
   */
  PUT = 1,

  /**
   * @generated from enum value: CHANGE_TYPE_DELETE = 2;
   */
  DELETE = 2,

  /**
   * @generated from enum value: CHANGE_TYPE_CLEAR = 3;
   */
  CLEAR = 3,
}

/**
 * @generated from message yorkie.v1.Presence
 */
export declare class Presence extends Message<Presence> {
  /**
   * @generated from field: map<string, string> data = 1;
   */
  data: { [key: string]: string };

  constructor(data?: PartialMessage<Presence>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Presence";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Presence;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Presence;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Presence;

  static equals(a: Presence | PlainMessage<Presence> | undefined, b: Presence | PlainMessage<Presence> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.Checkpoint
 */
export declare class Checkpoint extends Message<Checkpoint> {
  /**
   * @generated from field: int64 server_seq = 1 [jstype = JS_STRING];
   */
  serverSeq: string;

  /**
   * @generated from field: uint32 client_seq = 2;
   */
  clientSeq: number;

  constructor(data?: PartialMessage<Checkpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.Checkpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Checkpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Checkpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Checkpoint;

  static equals(a: Checkpoint | PlainMessage<Checkpoint> | undefined, b: Checkpoint | PlainMessage<Checkpoint> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.TextNodePos
 */
export declare class TextNodePos extends Message<TextNodePos> {
  /**
   * @generated from field: yorkie.v1.TimeTicket created_at = 1;
   */
  createdAt?: TimeTicket;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  /**
   * @generated from field: int32 relative_offset = 3;
   */
  relativeOffset: number;

  constructor(data?: PartialMessage<TextNodePos>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.TextNodePos";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TextNodePos;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TextNodePos;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TextNodePos;

  static equals(a: TextNodePos | PlainMessage<TextNodePos> | undefined, b: TextNodePos | PlainMessage<TextNodePos> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.TimeTicket
 */
export declare class TimeTicket extends Message<TimeTicket> {
  /**
   * @generated from field: int64 lamport = 1 [jstype = JS_STRING];
   */
  lamport: string;

  /**
   * @generated from field: uint32 delimiter = 2;
   */
  delimiter: number;

  /**
   * @generated from field: bytes actor_id = 3;
   */
  actorId: Uint8Array;

  constructor(data?: PartialMessage<TimeTicket>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.TimeTicket";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimeTicket;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimeTicket;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimeTicket;

  static equals(a: TimeTicket | PlainMessage<TimeTicket> | undefined, b: TimeTicket | PlainMessage<TimeTicket> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.DocEventBody
 */
export declare class DocEventBody extends Message<DocEventBody> {
  /**
   * @generated from field: string topic = 1;
   */
  topic: string;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;

  constructor(data?: PartialMessage<DocEventBody>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.DocEventBody";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocEventBody;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocEventBody;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocEventBody;

  static equals(a: DocEventBody | PlainMessage<DocEventBody> | undefined, b: DocEventBody | PlainMessage<DocEventBody> | undefined): boolean;
}

/**
 * @generated from message yorkie.v1.DocEvent
 */
export declare class DocEvent extends Message<DocEvent> {
  /**
   * @generated from field: yorkie.v1.DocEventType type = 1;
   */
  type: DocEventType;

  /**
   * @generated from field: string publisher = 2;
   */
  publisher: string;

  /**
   * @generated from field: yorkie.v1.DocEventBody body = 3;
   */
  body?: DocEventBody;

  constructor(data?: PartialMessage<DocEvent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "yorkie.v1.DocEvent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DocEvent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DocEvent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DocEvent;

  static equals(a: DocEvent | PlainMessage<DocEvent> | undefined, b: DocEvent | PlainMessage<DocEvent> | undefined): boolean;
}

