#!/usr/bin/env bash

# Copyright 2026 The Yorkie Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# Claude Code PreToolUse(Edit|Write) hook: refuse to hand-edit generated code.
#
# Two generators write committed TypeScript here, and an edit to either output
# is silently reverted the next time someone regenerates:
#
#   - `pnpm sdk build:proto` (buf + protoc-gen-es) writes
#     packages/sdk/src/api/yorkie/v1/*_pb.ts from the .proto beside them.
#   - `pnpm schema build:schema` (antlr4ts) writes
#     packages/schema/antlr/YorkieSchema{Lexer,Parser,Listener,Visitor}.ts
#     from YorkieSchema.g4.
#
# The .proto files are guarded too. They are copies: the source of truth is
# yorkie-team/yorkie's api/, and a change made only here diverges from the
# server. Syncing them is a copy, not an edit, so the refusal says so.
#
# FAIL OPEN. If node is missing or the payload is unreadable this allows the
# edit. A guard that vanishes is bad; a guard that stops someone without node
# from editing anything is worse.
#
# IT COVERS Edit AND Write, NOT Bash. The reach is "the tools an agent
# normally edits with", not "every path to the file".
#
# Protocol: the hook payload arrives as JSON on stdin. exit 0 allows, exit 2
# blocks and feeds stderr back to Claude as context.

payload=$(cat)

command -v node >/dev/null 2>&1 || exit 0

path=$(printf '%s' "$payload" | node -e '
let raw = "";
process.stdin.on("data", (c) => (raw += c));
process.stdin.on("end", () => {
  try {
    const p = JSON.parse(raw)?.tool_input?.file_path;
    process.stdout.write(typeof p === "string" ? p : "");
  } catch {
    process.stdout.write("");
  }
});
' 2>/dev/null) || exit 0

[ -n "$path" ] || exit 0

case "$path" in
  *packages/sdk/src/api/yorkie/v1/*_pb.ts)
    cat >&2 <<MSG
$path is generated by 'buf generate' and must not be hand-edited.

Its .proto is a copy of yorkie-team/yorkie's api/yorkie/v1/. Change the schema
there, copy the .proto here, then regenerate:

  pnpm sdk build:proto
MSG
    exit 2
    ;;
  *packages/sdk/src/api/yorkie/v1/*.proto)
    cat >&2 <<MSG
$path is a copy of yorkie-team/yorkie's api/yorkie/v1/, which is the source
of truth. Change it there first, then copy the file here verbatim and run
'pnpm sdk build:proto'. An edit made only here diverges from the server.
MSG
    exit 2
    ;;
  *packages/schema/antlr/*.ts)
    cat >&2 <<MSG
$path is generated by antlr4ts from packages/schema/antlr/YorkieSchema.g4 and
must not be hand-edited. Change the grammar, then regenerate:

  pnpm schema build:schema
MSG
    exit 2
    ;;
esac

exit 0
